<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
print('-----------------1D Array')
# 1D Array
A = np.array([1,2,3,4])
# print(A.shape)
print(A)

print('-----------------2D Array')
# 2D Array
B = np.array([[1, 2], [3, 5], [1, 7]])
# print(B.shape)
print(B)

print('-----------------3D Array')
# 3D Array
C = np.array([[[1, 5, 2], [8, 9, 5]], [[1, 7, 1], [2, 9, 4]]])
# print(C.shape)
print(C)


-----------------1D Array
[1 2 3 4]
-----------------2D Array
[[1 2]
 [3 5]
 [1 7]]
-----------------3D Array
(2, 2, 3)
[[[1 5 2]
  [8 9 5]]

 [[1 7 1]
  [2 9 4]]]
