<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

# Phần 1: Tạo mảng trong Python dùng numpy

print('-----------------1D Array')
# 1D Array
A = np.array([1,2,3,4])
# print(A.shape): #KQ: (4,)
print(A)

print('-----------------2D Array')
# 2D Array
B = np.array([[1, 2], [3, 5], [1, 7]])
# print(B.shape) #KQ: (3, 2)
print(B)

print('-----------------3D Array')
# 3D Array
C = np.array([[[1, 5, 2], [8, 9, 5]], [[1, 7, 1], [2, 9, 4]]])
#print(C.shape) #KQ: (2, 2, 3)
print(C)

# Phần 2: tạo nhanh các mảng có giá trị giống nhau trong numpy
# zeros() tạo ra mảng các giá trị đều bằng 0. Đầu vào là shape của array dưới dạng tuple
# ones() tạo ra mảng các giá trị đều bằng 1. Đầu vào là shape của array dưới dạng tuple
# full() tạo ra mảng các giá trị bằng nhau và bằng một số cho trước. Đầu vào là shape của array dưới dạng tuple và giá trị cho trước

print('-----------------#1D Array')
#1D Array
print('-----------------A_zeros')
A_zeros = np.zeros((4, ))
print(A_zeros) #[0. 0. 0. 0.]
print('-----------------A_ones')
A_ones = np.ones((4, ))
print(A_ones) #[1. 1. 1. 1.]
print('-----------------A_full')
A_full = np.full((4), 7)
print(A_full) #[7 7 7 7]

print('-----------------#2D Array')
#2D Array
print('-----------------B_zeros')
B_zeros = np.zeros((4, 3))
print(B_zeros) #[[0. 0. 0.]
               #[0. 0. 0.]
               #[0. 0. 0.]
               #[0. 0. 0.]]

print('-----------------B_ones')
B_ones = np.ones((4, 3))
print(B_ones) #[[1. 1. 1.]
               #[1. 1. 1.]
               #[1. 1. 1.]
               #[1. 1. 1.]]

print('-----------------B_full')
B_full = np.full((4, 3), 5)
print(B_full) #[[5 5 5]
              #[5 5 5]
              #[5 5 5]
              #[5 5 5]]

# print('-----------------#3D Array')
#3D Array
print('-----------------C_zeros')
C_zeros = np.zeros((2, 2, 3))
print(C_zeros) #[[[0. 0. 0.]
               #[0. 0. 0.]]

               #[[0. 0. 0.]
               #[0. 0. 0.]]]

print('-----------------C_ones')
C_ones = np.ones((2, 2, 3))
print(C_ones) #[[[1. 1. 1.]
               #[1. 1. 1.]]

               #[[1. 1. 1.]
               #[1. 1. 1.]]]

print('-----------------C_full')
C_full = np.full((2, 2, 3), 2)
print(C_full) #[[[2 2 2]
              #[2 2 2]]

              #[[2 2 2]
              #[2 2 2]]]

print('------Tạo ma trận đơn vị dùng np.eye()')
#Phần 3: Tạo ma trận đơn vị dùng np.eye()
D = np.eye(5)
print(D) #[[1. 0. 0. 0. 0.]
         #[0. 1. 0. 0. 0.]
         #[0. 0. 1. 0. 0.]
         #[0. 0. 0. 1. 0.]
         #[0. 0. 0. 0. 1.]]
print('------Tùy biến Array với np.arange')
#Phần 3: Tùy biến Array
#Tạo 1 Array giá trị chạy từ 0 -> 10
A_custom1 = np.arange(10)
print(A_custom1) #[0 1 2 3 4 5 6 7 8 9]

#Tạo 1 Array giá trị chạy từ 2 -> 10
A_custom2 = np.arange(2, 10)
print(A_custom2) #[2 3 4 5 6 7 8 9]

#Tạo 1 Array giá trị chạy từ 0 -> 30. Khoảng cách giữa các giá trị là 5.
A_custom3 = np.arange(0, 30, 5)
print(A_custom3) #[ 0  5 10 15 20 25]

#Tạo ma trận với các giá trị ngẫu nhiên sử dụng np.random.random()
A_random = np.random.random((2, 3))
print(A_random) #[[0.00642234 0.30249911 0.77283637]
                #[0.28173628 0.54638026 0.35927154]]




-----------------1D Array
[1 2 3 4]
-----------------2D Array
[[1 2]
 [3 5]
 [1 7]]
-----------------3D Array
[[[1 5 2]
  [8 9 5]]

 [[1 7 1]
  [2 9 4]]]
-----------------#1D Array
-----------------A_zeros
[0. 0. 0. 0.]
-----------------A_ones
[1. 1. 1. 1.]
-----------------A_full
[7 7 7 7]
-----------------#2D Array
-----------------B_zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------B_ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------B_full
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
-----------------C_zeros
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
-----------------C_ones
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
-----------------C_full
[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]
------Tạo ma trận đơn vị dùng np.eye()
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
------Tùy biến Array với np.arange
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25]
[[0.00642234 0.3024