<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Boardcasting chúng ta có thể dịch là lan truyền, cách mà chúng ta thay đổi đồng loạt giá trị nhiều phần tử của mảng.

Cụ thể hơn nữa Numpy cho phép thực hiện tính toán giữa các mảng với số và các mảng khác chiều với nhau.

In [6]:
import numpy as np

#Phần 1. Lan truyền mảng với 1 số (Cộng mảng với 1 số)
A = np.array([1,2,3,4])
A = A + 3
print(A) #[4 5 6 7]
#Ta thấy 3 đã cộng với tất cả phần tử của A, tương đương với numpy biến 3 thành mảng 1 chiều [3,3,3,3] để thực hiện phép cộng với A
#Tương tự với các phép trừ, phép nhân
#Mảng 2 chiều cũng dùng tương tự.
B = np.ones((10, 10))
print(B)
print('------Ket qua')
print(B*2)

#Phần 2. Phép cộng mảng khác chiều
C = np.array([[1, 2, 3], [3, 5, 2]])
D = np.array([1, 2, 3])
print(C + D)




[4 5 6 7]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
------Ket qua
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
[[2 4 6]
 [4 7 5]]
