<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
#Index và Slicing tương tự như List

A = np.array([
    [1, 2, 3, 4],
    [8, 9, 4, 5],
    [2, 9, 7, 8],
    [9, 6, 4, 9],
])

print(A)

# Phần 1: Truy cập hàng

# A. Truy cập hàng đầu tiên của ma trận'
print('A. Lấy hàng đầu tiên của ma trận')
print(A[0])

# B. Truy cập hàng cuối cùng của ma trận'
print('A. Lấy hàng cuối cùng của ma trận')
print(A[-1])


# Phần 2: Truy cập cột
# A. Truy cập cột đầu tiên của ma trận'
print('A. Lấy cột đầu tiên của ma trận')
print(A[:,0])

# B. Truy cập cột cuối cùng của ma trận'
print('B. Lấy cột cuối cùng của ma trận')
print(A[:, -1])

# C. Truy cập cột thứ 1 của ma trận: '
print('C. Lấy cột thứ 1 của ma trận')
print(A[:, 1])

# D. Truy cập mảng trong ma trận
# A = [[a00, a01, a02, a03],
#     [a10, a11, a12, a13],
#     [a20, a21, a22, a23],
#     [a30, a31, a32, a33]]
# Trong trường hợp của  A[1:3, 2:4] là cách để lát cắt một mảng hai chiều (A) để lấy một phạm vi con của nó.
# Trong lát cắt này, [1:3] Thì A[1:3] sẽ trả về một ma trận mới chứa các hàng từ hàng số 1 (bao gồm) đến hàng số 3 (không bao gồm hoặc là hàng 3 - 1) trong chiều đầu tiên
# và A[2:4] sẽ trả về một ma trận thứ 2 chứa các cột từ hàng số 12 (bao gồm) đến cột  số 4 (không bao gồm hoặc là hàng 4 - 1) trong chiều thứ 2
# giao 2 chiều này chính là kết quả
# Chú ý: Số thứ tự trong mảng được đánh từ 0
#Kết quả:
# [
#     [a12, a13],
#     [a22, a23]
# ]

print('D. Lấy mảng trong ma trận')
# print(np.shape(A))
print(A[1:3, 1:3])
#Phần 3: Truy cập phần tử cột

# Truy cập phần tử hàng 1 cột 3
print(A[1, 3])
print(A[1][3])


[[1 2 3 4]
 [8 9 4 5]
 [2 9 7 8]
 [9 6 4 9]]
A. Lấy hàng đầu tiên của ma trận
[1 2 3 4]
A. Lấy hàng cuối cùng của ma trận
[9 6 4 9]
A. Lấy cột đầu tiên của ma trận
[1 8 2 9]
B. Lấy cột cuối cùng của ma trận
[4 5 8 9]
C. Lấy cột thứ 1 của ma trận
[2 9 9 6]
D. Lấy mảng trong ma trận
[[9 4]
 [9 7]]
5
5
