<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Phép lặp (Iterating)

**1. Lặp các phần tử mảng 1 chiều**

In [2]:
import numpy as np

numA = np.arange(10)
for item in np.nditer(numA):
    print(item)


0
1
2
3
4
5
6
7
8
9


In [4]:
import numpy as np
A = np.array([1, 5, 2, 6, 7, 1, 4, 7, 9, 8])

for i in A:
    print(i)

1
5
2
6
7
1
4
7
9
8


**2. Lặp phần tử mảng 2 chiều**

In [13]:
import numpy as np
A  = np.random.randint(10, size=(3,4))

print(A)
for item in np.nditer(A):
    print(item)

[[8 0 1 3]
 [6 9 1 7]
 [5 5 4 5]]
8
0
1
3
6
9
1
7
5
5
4
5


**3. Lặp mảng 3 chiều**

In [17]:
import numpy as np

A =  np.random.randint(10, size = (2,3,2))
print(A)

for item in np.nditer(A):
    print(item)

[[[0 8]
  [5 9]
  [6 0]]

 [[6 1]
  [5 2]
  [7 2]]]
0
8
5
9
6
0
6
1
5
2
7
2


**4. Thay đổi giá trị trong quá trình lặp**
- Chú ý: Thêm cờ **op_flags = ['readwrite']** để bật chế độ có thể thay đổi các phần tử trong mảng



In [27]:
import numpy as np

A = np.random.randint(10, size=(5))
print(A)

# Chú ý: Thêm cờ op_flags = ['readwrite'] để bật chế độ có thể thay đổi các phần tử trong mảng
for item in np.nditer(A, op_flags = ['readwrite']):
    item[...] = item * 2
print(A)

[1 1 5 1 9]
[ 2  2 10  2 18]


**5. Lặp qua dòng**

In [34]:
import numpy as np

A = np.random.randint(10, size = (2,3))
print(A)

print('----------------------')
for item in np.nditer(A,  flags = ['external_loop'], order = 'F'):
    print(item)

print('----------------------')
for item in np.nditer(A,  flags = ['external_loop'], order = 'C'):
  print(item)

[[5 4 6]
 [6 6 9]]
----------------------
[5 6]
[4 6]
[6 9]
----------------------
[5 4 6 6 6 9]
