<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Phép lặp (Iterating)

1. Lặp các phần tử mảng 1 chiều

In [2]:
import numpy as np

numA = np.arange(10)
for item in np.nditer(numA):
    print(item)


0
1
2
3
4
5
6
7
8
9


In [4]:
import numpy as np
A = np.array([1, 5, 2, 6, 7, 1, 4, 7, 9, 8])

for i in A:
    print(i)

1
5
2
6
7
1
4
7
9
8


2. Lặp phần tử mảng 2 chiều

In [13]:
import numpy as np
A  = np.random.randint(10, size=(3,4))

print(A)
for item in np.nditer(A):
    print(item)

[[8 0 1 3]
 [6 9 1 7]
 [5 5 4 5]]
8
0
1
3
6
9
1
7
5
5
4
5
