<a href="https://colab.research.google.com/github/luongtvs/Python/blob/main/Numpy/manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Thay đổi - Manipulation**

**1. Thay đổi kích thước bảng**

**a. Trả về kích cỡ mảng shape**

In [3]:
import numpy as np

A = np.random.randint(10, size = (2, 4))
print(A)
print(A.shape)

[[3 7 5 0]
 [6 9 6 9]]
(2, 4)


**b. Thay đổi kích cỡ của mảng**
- Trả về mảng mới 3 chiều (2, 2, 2) từ mảng 2 chiều (2, 4)

In [5]:
A = np.random.randint(10, size = (2, 4))
print(A)
print(A.shape)
# reshape
print('-------reshape------')
B = A.reshape(2, 2, 2)
print(B)
print(B.shape)



[[0 5 4 6]
 [5 9 7 5]]
(2, 4)
-------reshape------
[[[0 5]
  [4 6]]

 [[5 9]
  [7 5]]]
(2, 2, 2)


**2. flatten()**
- Trả về mảng được dưỡi thành 1 chiều

In [7]:
import numpy as np

A = np.random.randint(10, size = (3, 3))
print(A)
# platten
print('-------platen--------')
B = A.flatten()
print(B)


[[8 2 6]
 [0 2 9]
 [1 2 4]]
-------platen--------
[8 2 6 0 2 9 1 2 4]


**3. expand_dims()**
- Trả về mảng mới được thêm chiều

In [12]:
import numpy as np

A = np.random.randint(10, size = (2, 3))
print(A)
print(A.shape)
# Mở rộng theo dòng axis=0
print('---Mở rộng theo dòng axis=0---')

B = np.expand_dims(A, axis = 0)
print(B)
print(B.shape)


# Mở rộng theo cột axis=1
print('---Mở rộng theo cột axis=1---')

C = np.expand_dims(A, axis = 1)
print(C)
print(C.shape)

[[5 3 2]
 [8 0 0]]
(2, 3)
---Mở rộng theo dòng axis=0---
[[[5 3 2]
  [8 0 0]]]
(1, 2, 3)
---Mở rộng theo cột axis=1---
[[[5 3 2]]

 [[8 0 0]]]
(2, 1, 3)


**4. squeeze()**
- Trả về mảng mới được giảm chiều

In [21]:
import numpy as np

A = np.random.randint(10, size = (1,2,3))
print(A)
print(A.shape)
# squeeze()
print('------squeeze()----------')
# Chỉ áp dụng với mảng có size (1, m, n)

B = np.squeeze(A, axis = 0)
print(B)
print(B.shape)



[[[6 4 7]
  [7 1 2]]]
(1, 2, 3)
------squeeze()----------
[[6 4 7]
 [7 1 2]]
(2, 3)


**5. Chuyển vị**
- Ma trận chuyển vị là ma chận chuyển hàng thành cột và cột thành hàng

In [22]:
import numpy as np

A = np.random.randint(10, size = (2, 4))
print(A)
print(A.shape)

print('-----------Chuyển vị--------')

B = A.T
print(B)
print(B.shape)

[[9 4 7 7]
 [1 5 0 2]]
(2, 4)
-----------Chuyển vị--------
[[9 1]
 [4 5]
 [7 0]
 [7 2]]
(4, 2)
